#if UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using System.Collections.Generic;

public class LinkAutoAssign : MonoBehaviour
{
    [MenuItem("AGV Tools/Auto Assign Link")]
    public static void AssignLink()
    {
        MapNode[] allNodes = FindObjectsOfType<MapNode>();
        if (allNodes.Length == 0)
        {
            Debug.LogError("연결할 수 있는 노드가 없습니다.");
            return;
        }

        GameObject linkRoot = GameObject.Find("Links_AutoGenerated");
        if (linkRoot == null)
        {
            linkRoot = new GameObject("Links_AutoGenerated");
        }

        int createdCount = 0;
        
        for (int i = 0; i < allNodes.Length; i++)
        {
            for (int j = 0; j < allNodes.Length; j++)
            {
                if (i == j) 
                    continue; 

                MapNode cur_node = allNodes[i];
                MapNode next_node = allNodes[j];

                Vector3 curPos = cur_node.transform.position;
                Vector3 nextPos = next_node.transform.position;
                                
                float distX = Mathf.Abs(curPos.x-nextPos.x);
                float distZ = Mathf.Abs(curPos.z- nextPos.z);

                bool isAlignedX = Mathf.Abs(curPos.x - nextPos.x) < 2.5f;
                bool isAlignedZ = Mathf.Abs(curPos.z - nextPos.z) < 1.0f;
                
                if(distX < 5f&&distZ<3f&&( isAlignedX || isAlignedZ))
                { 
                    string linkName = $"Link_{cur_node.nodeID}_to_{next_node.nodeID}";


                    if (GameObject.Find(linkName) != null) 
                        continue;
                    
                    GameObject linkObj = new GameObject(linkName);
                    linkObj.transform.SetParent(linkRoot.transform);


                    linkObj.transform.position = (curPos + nextPos) / 2.0f;

                    MapLink link = linkObj.AddComponent<MapLink>();
                    
                    link.fromNode = cur_node;
                    link.toNode = next_node;                                        

                    // 유니티 Undo(Ctrl+Z) 기록에 남기기
                    Undo.RegisterCreatedObjectUndo(linkObj, "Auto Create Link");

                    createdCount++;
                }
            }
        }

        Debug.Log($" 단방향 링크 자동 생성 완료! 총 {createdCount}개의 링크가 생성되었습니다.");
    }
}
#endif